title: 4akatun -> El Blog Cafetero...
iconURL: assets/4.png


# for a clean URL
permalink: :slug

social:
  twitter: akatunaso
  github: 4akatun

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
#hyvor_talk_website_id: 14
#google_analytics: UA-NNNNNNNN-N
